In [3]:
print('hello world')

hello world


In [4]:
import pandas as pd
import numpy as np 

In [5]:
a = np.arange(6, 12)

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
a = np.arange(6, 12)

In [8]:
a

array([ 6,  7,  8,  9, 10, 11])

In [9]:
b = np.array([4, 6, 45, 73])

In [10]:
b

array([ 4,  6, 45, 73])

In [11]:
a[0:4]

array([6, 7, 8, 9])

In [12]:
a[5:]

array([11])

In [13]:
a[::2]

array([ 6,  8, 10])

In [14]:
a[0, 3, -1]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [16]:
a[[0,3,-1]]

array([ 6,  9, 11])

In [17]:
a.dtype

dtype('int64')

**DIMENSIONS AND SHAPES**

In [18]:
A = np.array[
  [1,2,3],
  [4,5,6]
]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [89]:
A = np.array([
  [1,2,3],
  [4,5,6],
])

In [91]:
A[1,1]

np.int64(5)

In [20]:
A.shape

(2, 3)

In [21]:
A.ndim

2

In [23]:
B = np.array([
  [
    [1,3,5,7],
    [2,4,6,8],
    [5,10,15,20]
  ],
  [
    [2,3,5,7],
    [11,13,17,19],
    [4,8,12,16]
  ]
])

In [24]:
B.ndim

3

In [27]:
B.shape

(2, 3, 4)

In [26]:
B.shape

(2, 3, 4)

**INDEXING AND SLICING**

In [28]:
A[ : , 1:2]

array([[2],
       [5]])

In [29]:
B[ : , 1:4]

array([[[ 2,  4,  6,  8],
        [ 5, 10, 15, 20]],

       [[11, 13, 17, 19],
        [ 4,  8, 12, 16]]])

In [31]:
B[:, 2:4] # slicing for multi-dimensional matrices occur through the dimensions from the outer rows to inner rows and finally the columns. B is a 2 x 3 x 4 matrix

array([[[ 5, 10, 15, 20]],

       [[ 4,  8, 12, 16]]])

In [32]:
B.mean

<function ndarray.mean>

In [33]:
B.mean(axis=1) # asks for the mean of the array according to the rows with the number of columns of the result the same as the number of columns of the original array

array([[ 2.66666667,  5.66666667,  8.66666667, 11.66666667],
       [ 5.66666667,  8.        , 11.33333333, 14.        ]])

In [34]:
B.mean(axis=2) # asks for the mean of the array according to the columns with the number of columns of the result the same as the number of rows of the original array

array([[ 4.  ,  5.  , 12.5 ],
       [ 4.25, 15.  , 10.  ]])

In [35]:
B.mean(axis=0) # asks for the mean of the array according to slices available with the number of rows and columns of the result equal to the number of rows and columns of the original array

array([[ 1.5,  3. ,  5. ,  7. ],
       [ 6.5,  8.5, 11.5, 13.5],
       [ 4.5,  9. , 13.5, 18. ]])

In [36]:
B + 10 # this is an example of a broadcasted and vectorized operation


array([[[11, 13, 15, 17],
        [12, 14, 16, 18],
        [15, 20, 25, 30]],

       [[12, 13, 15, 17],
        [21, 23, 27, 29],
        [14, 18, 22, 26]]])

In [77]:
B > 10 # this is the operation of boolean arrays

NameError: name 'B' is not defined

In [79]:
pal = np.arange(5)

In [80]:
pal

array([0, 1, 2, 3, 4])

In [82]:
pal[[0,2]]

array([0, 2])

In [83]:
ad = np.array([1,2,3,4,5])

In [84]:
ad

array([1, 2, 3, 4, 5])

In [88]:
ad[0:2]

array([1, 2])

**INTRODUCTION TO PANDAS**

There are 2 data structures which are used in Pandas. They are: Series and Dataframes

In Series, they are similar to lists and dictionaries. Similar to lists, series are ordered--unlike dictionaries--but in contrast, they contain key and values like dictionaries--unlike lists which contain only values. In general, the advantage of a series is that it is an ordered sequence of elements, backed by numpy arrays which is very efficient and has an index which can take an label we pass--meaning we don't have to pass in numbers for indexes but labels. Also important to note is that using series in pandas, the upper limit of slicing is included in the result which is not done in normal Python.

In [22]:
population = pd.Series([35,60,45,55,70], index=['Canada', 'France', 'Germany', 'Indonesia', 'Georgia'], name='Population in Countries')

In [92]:
population

Canada       35
France       60
Germany      45
Indonesia    55
Georgia      70
Name: Population in Countries, dtype: int64

In [93]:
population[1:4]

France       60
Germany      45
Indonesia    55
Name: Population in Countries, dtype: int64

In [94]:
population['France': 'Georgia']

France       60
Germany      45
Indonesia    55
Georgia      70
Name: Population in Countries, dtype: int64

In [25]:
population['Canada']

np.int64(35)

In [96]:
population[(population > 50) & (population < 65)]

France       60
Indonesia    55
Name: Population in Countries, dtype: int64

In [26]:
pd.Series(population, index=['Canada'])

Canada    35
Name: Population in Countries, dtype: int64

In [27]:
population[['Canada']]

Canada    35
Name: Population in Countries, dtype: int64

In [28]:
population['Canada':'Indonesia']

Canada       35
France       60
Germany      45
Indonesia    55
Name: Population in Countries, dtype: int64

In [39]:
population['Canada':'Indonesia']

Canada       35
France       60
Germany      45
Indonesia    55
Name: Population in Countries, dtype: int64

In [30]:
population

Canada       35
France       60
Germany      45
Indonesia    55
Georgia      70
Name: Population in Countries, dtype: int64

In [31]:
population > 50

Canada       False
France        True
Germany      False
Indonesia     True
Georgia       True
Name: Population in Countries, dtype: bool

In [32]:
population[population > 50]

France       60
Indonesia    55
Georgia      70
Name: Population in Countries, dtype: int64

In [33]:
population.mean()

np.float64(53.0)

In [34]:
population[population > 50].mean()

np.float64(61.666666666666664)

In [97]:
population.iloc[[-1]]

Georgia    70
Name: Population in Countries, dtype: int64

In [36]:
population.iloc[-1]

np.int64(70)

In [37]:
population.iloc[[-1]]

Georgia    70
Name: Population in Countries, dtype: int64

In [99]:
population.loc[['France']]

France    60
Name: Population in Countries, dtype: int64

**DATAFRAMES IN PANDAS**

While using Pandas for analysis, dataframes are more likely to be used than series although both data structures still get to play important roles in themselves. Dataframes are like a combination of series. One per column. 

There are two methods for dataframes which are used and are important for analysis. They are: the .loc()and the .iloc(). These methods return the information of a particular index(horizontal) and then transpose it (vertical) creating a series(result). Examples are given below.

The .loc() method works with inputting labels as parameters while the iloc() method works with inputting the sequential position of the index(numbers). Again, the results of both methods are series.

Other methods that can used on the dataframe include: .describe(), .dtype(), .info(),rtc. Attributes include: .size, .shape, .columns, .index, etc.

In [46]:
data = pd.DataFrame(
  {'Population': [35, 45, 75, 40, 26, 47, 83, 72], 
   'Continent': ['Europe', 'Asia', 'Africa', 'Africa', 'Europe', 'S/America', 'Asia', 'Africa'],
   'Love': [5, 7, 2, 3, 6, 6, 4, 2]
   },
   index= ['Albania', 'China', 'Nigeria', 'Gabon', 'Germany', 'Argentina', 'India', 'Botswana']
)

In [100]:
data['Population'].to_frame()

Population
Albania            35
China              45
Nigeria            75
Gabon              40
Germany            26
Argentina          47
India              83
Botswana           72

In [ ]:
data['Population']

Albania      35
China        45
Nigeria      75
Gabon        40
Germany      26
Argentina    47
India        83
Botswana     72
Name: Population, dtype: int64

In [47]:
data

Population  Continent  Love
Albania            35     Europe     5
China              45       Asia     7
Nigeria            75     Africa     2
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6
India              83       Asia     4
Botswana           72     Africa     2

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Albania to Botswana
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Population  8 non-null      int64 
 1   Continent   8 non-null      object
 2   Love        8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 256.0+ bytes


In [49]:
data.size

24

In [50]:
data.shape

(8, 3)

In [51]:
data.describe()

Population     Love
count    8.000000  8.00000
mean    52.875000  4.37500
std     20.931436  1.92261
min     26.000000  2.00000
25%     38.750000  2.75000
50%     46.000000  4.50000
75%     72.750000  6.00000
max     83.000000  7.00000

In [52]:
data.dtypes

Population     int64
Continent     object
Love           int64
dtype: object

In [53]:
data.loc['Nigeria']

Population        75
Continent     Africa
Love               2
Name: Nigeria, dtype: object

In [54]:
data.iloc[-2]

Population      83
Continent     Asia
Love             4
Name: India, dtype: object

In [55]:
data['Population']

Albania      35
China        45
Nigeria      75
Gabon        40
Germany      26
Argentina    47
India        83
Botswana     72
Name: Population, dtype: int64

In [57]:
data[['Population', 'Love']]

Population  Love
Albania            35     5
China              45     7
Nigeria            75     2
Gabon              40     3
Germany            26     6
Argentina          47     6
India              83     4
Botswana           72     2

In [58]:
data[1:3]

Population Continent  Love
China            45      Asia     7
Nigeria          75    Africa     2

In [109]:
data.loc['Argentina':'Botswana', 'Population':'Love']

Population  Continent  Love
Argentina          47  S/America     6
India              83       Asia     4
Botswana           72     Africa     2

In [59]:
data.iloc[1:3]

Population Continent  Love
China            45      Asia     7
Nigeria          75    Africa     2

In [61]:
data.iloc[[0, 1, -1]]

Population Continent  Love
Albania           35    Europe     5
China             45      Asia     7
Botswana          72    Africa     2

In [65]:
data.iloc[1:3, 2]

China      7
Nigeria    2
Name: Love, dtype: int64

In [67]:
data.iloc[0: , [1,2]]

Continent  Love
Albania       Europe     5
China           Asia     7
Nigeria       Africa     2
Gabon         Africa     3
Germany       Europe     6
Argentina  S/America     6
India           Asia     4
Botswana      Africa     2

In [68]:
data.loc['Nigeria': 'Argentina']

Population  Continent  Love
Nigeria            75     Africa     2
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6

In [110]:
data.loc['Germany':'Botswana', ['Population', 'Continent']]

Population  Continent
Germany            26     Europe
Argentina          47  S/America
India              83       Asia
Botswana           72     Africa

In [119]:
data.loc['Bahrain'] = pd.Series({'Population': 67, 'Continent': 'Asia', 'Love': 3})

In [115]:
data

Population  Continent  Love
Albania            35     Europe     5
China              45       Asia     7
Nigeria            75     Africa     2
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6
India              83       Asia     4
Botswana           72     Africa     2
Bahrain            67       Asia     3

In [124]:
data.loc['Croatia'] = pd.Series({'Population': 43, 'Continent': 'Europe', 'Love': 6,}, name = 'Bel')

In [125]:
data

Population  Continent  Love
Albania            35     Europe     5
China              45       Asia     7
Nigeria            75     Africa     2
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6
India              83       Asia     4
Botswana           72     Africa     2
Bahrain            67       Asia     3
Croatia            43     Europe     6

In [122]:
data

Population  Continent  Love
Albania            35     Europe     5
China              45       Asia     7
Nigeria            75     Africa     2
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6
India              83       Asia     4
Botswana           72     Africa     2
Bahrain            67       Asia     3
Croatia            43     Europe     6

In [72]:
data[['Population']]

Population
Albania            35
China              45
Nigeria            75
Gabon              40
Germany            26
Argentina          47
India              83
Botswana           72

In [74]:
data.drop(['Nigeria', 'Botswana'])

Population  Continent  Love
Albania            35     Europe     5
China              45       Asia     7
Gabon              40     Africa     3
Germany            26     Europe     6
Argentina          47  S/America     6
India              83       Asia     4

In [75]:
data.drop(columns='Love')

Population  Continent
Albania            35     Europe
China              45       Asia
Nigeria            75     Africa
Gabon              40     Africa
Germany            26     Europe
Argentina          47  S/America
India              83       Asia
Botswana           72     Africa