In [2]:
import pandas as pd
import numpy as np

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
file_path = "Customer-Table.csv"
data = pd.read_csv(file_path)
data.head()

customer_id               name                 address             city  \
0         1980  Leocadia Andersen  7015 Fairground Street         Dearborn   
1         2463        Chad Lucero     142 Wakehurst Drive      Santa Clara   
2         1978      Stone Randall    898 Peninsula Circle  Oakland Gardens   
3         9383       Emelia Braun     101 Military Street       Blacksburg   
4         8940       Ridley Velez    280 Pennington Drive         Clemmens   

  state  zipcode country  
0    MI    48124      US  
1    CA    95050      US  
2    NY    11364      US  
3    VA    24060      US  
4    NC    27012      US

In [6]:
data.shape

(29, 7)

In [7]:
data = pd.read_csv(file_path)

In [8]:
data.head()

customer_id               name                 address             city  \
0         1980  Leocadia Andersen  7015 Fairground Street         Dearborn   
1         2463        Chad Lucero     142 Wakehurst Drive      Santa Clara   
2         1978      Stone Randall    898 Peninsula Circle  Oakland Gardens   
3         9383       Emelia Braun     101 Military Street       Blacksburg   
4         8940       Ridley Velez    280 Pennington Drive         Clemmens   

  state  zipcode country  
0    MI    48124      US  
1    CA    95050      US  
2    NY    11364      US  
3    VA    24060      US  
4    NC    27012      US

In [9]:
data.dtypes

customer_id     int64
name           object
address        object
city           object
state          object
zipcode         int64
country        object
dtype: object

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   customer_id  29 non-null     int64 
 1   name         29 non-null     object
 2   address      29 non-null     object
 3   city         29 non-null     object
 4   state        29 non-null     object
 5   zipcode      29 non-null     int64 
 6   country      29 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.7+ KB


In [11]:
data = pd.read_csv(
  file_path,
  index_col=0
)

In [12]:
data.head()

name                 address             city state  \
customer_id                                                                     
1980         Leocadia Andersen  7015 Fairground Street         Dearborn    MI   
2463               Chad Lucero     142 Wakehurst Drive      Santa Clara    CA   
1978             Stone Randall    898 Peninsula Circle  Oakland Gardens    NY   
9383              Emelia Braun     101 Military Street       Blacksburg    VA   
8940              Ridley Velez    280 Pennington Drive         Clemmens    NC   

             zipcode country  
customer_id                   
1980           48124      US  
2463           95050      US  
1978           11364      US  
9383           24060      US  
8940           27012      US

In [13]:
3 + np.nan

nan

In [14]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [15]:
a.sum()

np.float64(nan)

In [16]:
a.mean()


np.float64(nan)

In [17]:
np.inf

inf

In [18]:
np.inf/np.inf

nan

In [19]:
# b = np.array([1, 2, 3, np.nan, np.inf, 4], dtype=np.float)

In [20]:
np.isnan(np.nan)


np.True_

In [21]:
np.isinf(np.inf)

np.True_

In [22]:
np.isfinite(np.nan), np.isfinite(np.inf)

(np.False_, np.False_)

In [23]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [24]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [25]:
pd.isnull(np.nan)

True

In [26]:
pd.Series([True, False, False]).any()

np.True_

In [27]:
pd.Series([True, False, False]).all()

np.False_

In [29]:
df = pd.DataFrame({
  'Sex': ['M','F', 'M', 'D', '?'],
  'Age': [35, 48, 480, 25, 340]
})

In [30]:
df

Sex  Age
0   M   35
1   F   48
2   M  480
3   D   25
4   ?  340

In [31]:
df['Age'] > 100

0    False
1    False
2     True
3    False
4     True
Name: Age, dtype: bool

In [33]:
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age']/10

In [34]:
df

Sex  Age
0   M   35
1   F   48
2   M   48
3   D   25
4   ?   34

In [39]:
df.replace({
  'Sex': {'D':'F', 'N': 'M'},
  'Age': {25:30}
})

Sex  Age
0   M   35
1   F   48
2   M   48
3   F   30
4   ?   34

In [40]:
df.dtypes

Sex    object
Age     int64
dtype: object